blank_issues_enabled: false
contact_links:
    - name: Ask a Question
      url: https://github.com/mtex-toolbox/mtex/discussions/new?category_id=32000416
      about: Ask a question about this project.
